### ISSUE TITLE
Action not allowed on a base admin account

### ISSUE THREAD

**Issue by 420connect** [Spuds/SMF-Admin-Toolbox#1]
Hey,

I was just directed towards this mod for SMF that I installed and whilst trying to merge a member account with my own (Admin) - I recieved a message saying 'Action not allowed on a base admin account' and wondered if there was any 'hack' to bypass this? or why it isn't allowed..

Thank you

**Comment by 420connect** [comment]
Just wanted to add a link to where this original discussion started to help share any possible answers..
(and I'll probably forget I made this 'issue' :P - I dont really use GH much..)

http://www.simplemachines.org/community/index.php?topic=535562.0

Kind Regards

**Comment by Spuds** [comment]
Thats just a restriction I put in place, as generally jacking with the admin account is not one of the best things to do.  It would also allow an admin to easily grab the PM's of another member which is way not cool.

So with those comments .... if you open up the AdminToolbox.php file you will find the following lines starting at 1023
```
 	// Not a good idea with the admin account either
	if (($_POST['merge_to'] == 1) || ($_POST['merge_from'] == 1))
		redirectexit('action=admin;area=toolbox;error=adminid');
```
If you are trying to merge into the admin account, just change that to be
```
 	// Not a good idea with the admin account either
	if (($_POST['merge_from'] == 1)
		redirectexit('action=admin;area=toolbox;error=adminid');
```
should then allow that to happen ... be sure and backup of course (standard disclosure) ;)
