### ISSUE TITLE
Merge Member Issue

### ISSUE THREAD

**Issue by PhuriousGeorge** [Spuds/SMF-Admin-Toolbox#3]
Cleaning up an old forum I just brought back to life and have been merging duplicate members with the toolbox.  Seemed to be working fine until just recently I've been getting:

`The database value you're trying to insert does not exist: p_date_registered`

Here's the Error log from SMF:
`http://www.genesisgamers.com/index.php?action=admin;area=toolbox;sa=merge;step=7;ecfa3cc3a=b5d1f6ac936c8e21839fb32260a0955e
The database value you're trying to insert does not exist: p_date_registered
Function: updateMemberDataApply /var/www/html/vhosts/genesisgamers.com/htdocs/Sources/Subs.php
Line: 547`

and

`http://www.genesisgamers.com/index.php?action=admin;area=toolbox;sa=merge;step=7;ecfa3cc3a=b5d1f6ac936c8e21839fb32260a0955e
8: Undefined offset: 291
File: /var/www/html/vhosts/genesisgamers.com/htdocs/Sources/AdminToolbox.php
Line: 1356`

Any idea what I've botched up?

**Comment by Spuds** [comment]
Looks like that some member does not have a join date in their profile ... the second error would look to mean that member id 291 is missing some information (join date) and that should not be missing (or at least the program does not anticipate that would be missing)

**Comment by PhuriousGeorge** [comment]
Looking at my db, all users have a registered date in the members table.
Is there another table I should be looking at?  I did scrape a bunch of old
posts and users from a forumotion forum some time ago, perhaps I missed
back filling something.

**Comment by Spuds** [comment]
What version of SMF are you using ?

**Comment by PhuriousGeorge** [comment]
2.0.11 currently

**Comment by Spuds** [comment]
I should have said to look at the signature line for 291, thats the line 1356 error.  Do you only get the error with that member?

**Comment by PhuriousGeorge** [comment]
That's the first time I've noticed that second error.  Added it hopong it
might help diagnose error 1, which has halted any merging attempts I've
made lately..

Odd thing is iser 291 doesn't even exist...

I'll have to poke it harder once I get home from work.

On May 2, 2016 12:27 PM, "Spuds" <notifications@github.com> wrote:
>
> I should have said to look at the signature line for 291, thats the line
1356 error. Do you only get the error with that member?

**Comment by PhuriousGeorge** [comment]
So I tested more and continue to receive the "p_date_registered" error.  I reviewed the database and every member has a "date_registered" entry.  Does the extra "p_" in the listed error message mean anything?

I just realized I only have one account left to merge.  I can do it manually, just trying to figure out if I botched something up and need to refer to backups though not much has changed except removing a few tables no longer in use by modifications I tested on the live board ages ago.

**Comment by Spuds** [comment]
> Does the extra "p_" in the listed error message mean anything?

I believe that is something SMF adds, its not part of the mod.

Since I'm kind of in the dark on this, the only thing you could do is test is
```
		// update the new ID with the combined user data
		updateMemberData($dstid, $new_data);
```
change to
```
		// update the new ID with the combined user data
var_dump($dstid, $new_data);die;
		updateMemberData($dstid, $new_data);
```
Just to see what is being passed to Subs.php and maybe that will help determine why it fails

**Comment by PhuriousGeorge** [comment]
You think you're in the dark? :)  I'm trying to learn lol.  I'm hoping to figure out the differences in SMF and Elk and do some ports, but I'm still a nub.

Anywho, here's what it spit out:
`int(292) array(23) { ["karma_bad"]=> int(0) ["karma_good"]=> int(0) ["total_time_logged_in"]=> int(0) ["date_registered"]=> NULL ["personal_text"]=> NULL ["gender"]=> string(1) "1" ["birthdate"]=> string(10) "0004-10-11" ["website_title"]=> NULL ["website_url"]=> NULL ["location"]=> NULL ["icq"]=> NULL ["aim"]=> NULL ["yim"]=> NULL ["msn"]=> NULL ["hide_email"]=> NULL ["show_online"]=> string(1) "1" ["avatar"]=> NULL ["signature"]=> NULL ["pm_email_notify"]=> NULL ["notify_announcements"]=> string(1) "1" ["notify_regularity"]=> string(1) "1" ["notify_send_body"]=> NULL ["notify_types"]=> string(1) "2" }`

**Comment by Spuds** [comment]
Interesting that "date_registered" is null ... that can be fixed in the code of course, but that would mask the issue of why is that null  .... that value should not ever be null in the DB.  Is member id 292  a valid member?

**Comment by PhuriousGeorge** [comment]
Odd... 292 is a valid member, but I was actually merging 277 & 278...

All 3 have entries for date registered in phpmyadmin though

**Comment by Spuds** [comment]
Odd indeed ! not sure what to make of that.

**Comment by PhuriousGeorge** [comment]
Curiosity encourages me to keep digging, but not seeing any other issues or
posts with related problems, I can't help but think something is screwy
with the merge I did previously.  I haven't had any other related problems
that I've noticed.  Since most of these members and posts are inactive,
I'll just make the manual merge.  Feel free to close & thanks!
